### ISSUE TITLE
The unit of Green's function (displacement/velocity)

### ISSUE THREAD

**Issue by VioletaSeo** [YunyiQian/grtm#1]
Hi. Thanks for developing such an efficient program for calculating synthetics.
By the way, I was comparing two Green's functions computed from FK 3.3 and GRTM and found that their results slightly differ. Up to what I know, FK 3.3 GFs are velocities so they should be integrated to obtain displacement. Therefore, I was suspecting that this difference stems from the fact that GRTM GFs represent displacements while FK GFs are velocities. However, I could not figure out whether my guess is correct so I want to ask if this guess is right.

I experimented with the two following codes with same 1D model "hk":

1) For FK 3.3
fk.pl -Mhk/15/k -N512/0.1 05 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80

2) for GRTM
grtm.pl -Mhk/15/k -N9/0.1 05 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80

**Comment by YunyiQian** [comment]
Hi. Thanks for your interesting&nbsp; of our grtm code. Indeed, the output type of grtm is the same as that of fk, you could use syn in fk to integrate the Green's functions of grtm to obtain synthetic displacement waveform. The current uploaded grtm code is only used for single force sources, such if you use fk to benchmark, you need to use -S option to choose the source type:


fk.pl -Mhk/15/k -S1 -N512/0.1 05 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80


if you do not use -S, fk actually use -S2 (double couple source).


Best wishes,
Yunyi









钱韵衣
南方科技大学


 联系我









&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Lucas ***@***.***&gt;;
Date: &nbsp;Fri, Sep 17, 2021 09:02 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[YunyiQian/grtm] The unit of Green's function (displacement/velocity) (#1)

&nbsp;



 
Hi. Thanks for developing such an efficient program for calculating synthetics.
 By the way, I was comparing two Green's functions computed from FK 3.3 and GRTM and found that their results slightly differ. Up to what I know, FK 3.3 GFs are velocities so they should be integrated to obtain displacement. Therefore, I was suspecting this difference stems from the fact that GRTM GFs represent displacements while FK GFs are velocities. However, I could not figure out whether my guess is correct so I want to ask if this guess is right.
 
I experimented with the two following codes with same 1D model "hk":
  
 
For FK 3.3
 fk.pl -Mhk/15/k -N512/0.1 05 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80
 
 
 
for GRTM
 grtm.pl -Mhk/15/k -N9/0.1 05 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80
 
  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VioletaSeo** [comment]
Thanks! I got the same results for fk and grtm after adding option `-S1` for fk.pl.
